{% set name = "safehttpx" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/safehttpx-{{ version }}.tar.gz
  sha256: 6e1bedf7767213300da5e4cb7e823e98edc934f17ca192d2e585111a2b899149

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx

test:
  imports:
    - safehttpx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A small Python library created to help developers protect their applications from Server Side Request Forgery (SSRF) attacks.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/gradio-app/safehttpx
  description: A small Python library created to help developers protect their applications from Server Side Request Forgery (SSRF) attacks. It implements an **asynchronous GET method** called `safehttpx.get()`, which is a wrapper around `httpx.AsyncClient.get()` while performing DNS validation on the supplied URL using [Google DNS](https://developers.google.com/speed/public-dns). 

extra:
  recipe-maintainers:
    - HeavyTony2
